#!/bin/bash
PACKAGE_DIR=/var/vcap/packages/jenkins
JAVA_DIR=/var/vcap/packages/java
GIT_DIR=/var/vcap/packages/git
JOB_DIR=/var/vcap/jobs/jenkins
DATA_DIR=/var/vcap/store/jenkins
RUN_DIR=/var/vcap/sys/run/jenkins
LOG_DIR=/var/vcap/store/log/
WEBROOT=/var/vcap/store/run/jenkins

JENKINS_HOME=$DATA_DIR
PIDFILE=$RUN_DIR/jenkins.pid
JENKINS_WAR=$PACKAGE_DIR/jenkins.war

HTTP_PORT=<%= properties.jenkins.http_port || 8080 %>
JENKINS_ARGS="--prefix=/jenkins --webroot=$WEBROOT --httpPort=$HTTP_PORT --ajp13Port=-1"

COMMAND="java -Xmx2048m -jar $JENKINS_WAR $JENKINS_ARGS"

case "$1" in
  start)
    mkdir -p $RUN_DIR $LOG_DIR $DATA_DIR $WEBROOT

    chown -R vcap:vcap $RUN_DIR $LOG_DIR $DATA_DIR $WEBROOT

    chown vcap:vcap $JENKINS_WAR

    echo $$ > $PIDFILE
    ulimit -n 8192

    $JOB_DIR/bin/change_tmp

    # Add Slaves configs etc
    $JOB_DIR/bin/jenkins_init.ctl

    su - vcap -c "JENKINS_HOME=$DATA_DIR LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH PATH=$JAVA_DIR/bin/:$GIT_DIR/bin/:$PATH $COMMAND >>$LOG_DIR/jenkins.stdout.log 2>>$LOG_DIR/jenkins.stderr.log"
    ;;

  stop)
    echo "Stopping Jenkins "
    PID=$(head -1 $PIDFILE)

    killall java

    while [ -e /proc/$PID ]; do sleep 0.1; done
     rm -f $PIDFILE
    ;;

  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
