#!/bin/bash
RUN_DIR=/var/vcap/sys/run/jenkins
DATA_DIR=/var/vcap/store/jenkins
LOG_DIR=/var/vcap/store/log
BACKUP_LOG=jenkins_backup.log
TERMINATE_BACKUP=/tmp/terminate_backup
MONIT_FILE=/var/vcap/jobs/jenkins/jenkins.monitrc

log() {
  timenow=`date "+%Y-%m-%d %H:%M:%S"`
  find $LOG_DIR -maxdepth 1 -ctime +5 -name $BACKUP_LOG | grep "$BACKUP_LOG"
  [ $? == 0 ] && mv $LOG_DIR/$BACKUP_LOG $LOG_DIR/${BACKUP_LOG}.1
  echo "$timenow $1" >> $LOG_DIR/$BACKUP_LOG
}

jenkins_master_id=1
jenkins_address=<%= properties.jenkins.address %>
/sbin/ifconfig | grep $jenkins_address
[ $? == 0 ] || jenkins_master_id=2

jenkins_backup_address=<%= properties.jenkins.backup_address %>
[ -z "$jenkins_backup_address" ] && exit 1

if [ $jenkins_master_id == 2 ]; then
  cat $MONIT_FILE | grep "$jenkins_backup_address"
  if [ $? != 0 ]; then
    cat $MONIT_FILE | sed -e "s/$jenkins_address/$jenkins_backup_address/g" > /tmp/jenkins.monitrc
    sudo mv /tmp/jenkins.monitrc $MONIT_FILE
    sudo /var/vcap/bosh/bin/monit reload
    sleep 20
    sudo /var/vcap/bosh/bin/monit restart all
  fi
  [ -f $TERMINATE_BACKUP ] && rm $TERMINATE_BACKUP
  exit 0
fi

LAST_BAK_FILE=$DATA_DIR/last_backup_time
LAST_RESTART_FILE=$DATA_DIR/last_restart_time
backup_interval=<%= properties.jenkins.backup_interval || 20 %> #unit: min
restart_interval=<%= properties.jenkins.restart_interval || 12 %> #unit: hour
backup_interval_secs=$((backup_interval * 60))
restart_interval_secs=$((restart_interval * 60 * 60))

[ -f $TERMINATE_BACKUP ] && rm $TERMINATE_BACKUP
while true
do
  sleep 20
  [ -f $TERMINATE_BACKUP ] && exit 0

  last_backup=0
  [ -f $LAST_BAK_FILE ] && last_backup=`head -1 $LAST_BAK_FILE`

  last_restart=0
  [ -f $LAST_RESTART_FILE ] && last_restart=`head -1 $LAST_RESTART_FILE`

  now=`date +%s`
  ps $JENKINS_PID
  if [ $? == 0 ] && (( $now - $last_backup > $backup_interval_secs )); then
    log "Prepare for starting sync to $jenkins_backup_address:$DATA_DIR/"
    rsync -avz $DATA_DIR/jobs vcap@$jenkins_backup_address:$DATA_DIR/ | grep "jobs" >> $LOG_DIR/$BACKUP_LOG
    echo $now > $LAST_BAK_FILE
  fi

  now=`date +%s`
  ps $JENKINS_PID
  if [ $? == 0 ] && (( $now - $last_restart > $restart_interval_secs )); then
    log "Retart remote jenkins $jenkins_backup_address"
    ssh vcap@$jenkins_backup_address "sudo /var/vcap/bosh/bin/monit restart jenkins"
    echo $now > $LAST_RESTART_FILE
  fi
done
