#!/bin/bash

RUN_DIR=/var/vcap/sys/run/warden
LOG_DIR=/var/vcap/sys/log/warden
PIDFILE=$RUN_DIR/warden.pid
WARDEN_CONF_DIR=/var/vcap/jobs/jenkins_slave/config
FIRSTRUN_PATH=$RUN_DIR/firstrun
QUOTA_FS=/var/vcap/data

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    cd /var/vcap/packages/warden/warden

    export PATH=/var/vcap/packages/ruby/bin:$PATH
    exec /var/vcap/packages/ruby/bin/bundle exec rake warden:start[$WARDEN_CONF_DIR/warden.yml] >>$LOG_DIR/warden.stdout.log 2>>$LOG_DIR/warden.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: warden_ctl {start|stop}" ;;
esac
exit 0
