#!/bin/bash
STORE_DIR=/var/vcap/store/mysql
LOG_DIR=/var/vcap/sys/log/mysql
RUN_DIR=/var/vcap/sys/run/mysqld
MYSQL_DIR=/var/vcap/packages/mysql
JOB_DIR=/var/vcap/jobs/gerrit_mysql
CONFIG_DIR=$JOB_DIR/config
PIDFILE=$RUN_DIR/mysqld.pid

case $1 in

  start)
    $MYSQL_DIR/libexec/mysql.server start $CONFIG_DIR/my.cnf

    su - vcap -c "$JOB_DIR/bin/setup_slave"
    ;;

  stop)
    echo "Stopping Gerrit_mysql"
    $MYSQL_DIR/libexec/mysql.server stop $CONFIG_DIR/my.cnf
    rm $PIDFILE
    ;;

  *)
  echo "Usage: mysql_ctl {start|stop}" ;;
esac
exit 0
