#!/bin/bash
RUN_DIR=/var/vcap/sys/run/replication/
PIDFILE=$RUN_DIR/replication.pid
GIT_DIR=/var/vcap/packages/git

case $1 in

  start)
    mkdir -p /var/vcap/shared
    mkdir -p $RUN_DIR

    echo $$ > $PIDFILE

    #The replication invoked by gerrit instance seems don't lookup env for git, copy it to /usr/bin fix it. need harden?
    cp -rf $GIT_DIR/bin/* /usr/bin/

    if grep -qs /var/vcap/shared /proc/mounts; then
      echo "Found NFS mount"
    else
      echo "Mounting NFS..."
      mount -t nfs  <%= properties.nfs_server.address %>:/var/vcap/store/shared /var/vcap/shared

      if [ $? != 0 ]; then
        echo "ERROR: Unable to Mount NFS from <%= properties.nfs_server.address %>:/var/vcap/shared"
        exit 1
      fi
    fi

    su - vcap -c "mkdir -p /var/vcap/shared/gerrit_replication/<%= properties.gerrit_postgres.dbname %>"

    #vcap ssh key repo
    mkdir -p /home/vcap/.ssh/
    chown vcap:vcap /home/vcap/.ssh/

    #renew vcap passwd
    pass=`perl -e 'print crypt("<%= properties.gerrit_replication.password %>", "ab")'`
    usermod -p $pass vcap
    # Now nothing need watching, just give it to init
    echo 1 > $PIDFILE
    ;;

  stop)
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: replication_ctl {start|stop}" ;;
esac
exit 0
