---



service_name: mysql
snapshots_base_dir: /var/vcap/service_lifecycle
serialization_base_dir: /var/vcap/service_lifecycle
local_db: sqlite3:/var/vcap/store/mysql_node.db
tmp_dir: /var/vcap/service_lifecycle/tmp_dir
resque:
  host: 10.42.244.82
  port: 3456
  password: bt3FXngo
  expire: 
logging:
  level: debug
  file: /var/vcap/sys/log/mysql_node/mysql_worker.log
  
  syslog: vcap.mysql_worker
  
index: 0
node_id: mysql_node_200_0
download_url_template: "http://service-serialization.cf175.dev.las01.vcsops.com/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}"
snapshot_quota: 2
serialization:
  max_download_size_mb: 10
# addtional options
mysql:

  5.5:
    host: localhost
    port: 3307
    socket: /var/vcap/sys/run/mysqld/mysqld55.sock
    user: root
    pass: zb213djkas
    mysqldump_bin:  /var/vcap/packages/mysql55/bin/mysqldump
    mysql_bin:  /var/vcap/packages/mysql55/bin/mysql

gzip_bin: /bin/gzip

use_warden: true


