---

service_name: mysql
backup_base_dir: /var/vcap/services_backup
backup_cmd: /var/vcap/packages/mysql/bin/mysqldump --host=:host --user=:user --password=:passwd -S :socket --result-file=:full_path/:name.sql -R --single-transaction :name
compress_cmd: /bin/gzip :full_path/:name.sql
logging:
  file: /var/vcap/sys/log/mysql_node/mysql_backup.log
  level: debug
  
  syslog: vcap.mysql_backup
  
mysql:
  host: localhost
  port: 3306
  user: root
  pass: zb213djkas
  socket: /var/vcap/sys/run/mysqld/mysqld.sock
timeout: 600
node_id: mysql_node_200_0
pid: /var/vcap/sys/run/mysql_node/mysql_backup.pid

  use_warden: true

