---
server:
  container_klass: Warden::Container::Linux
  container_grace_time: ~
  container_rootfs_path: /var/vcap/data/warden/rootfs
  container_depot_path: /var/vcap/store/containers
  unix_domain_permissions: 0777
logging:
  file: /var/vcap/sys/log/warden/warden.log
  
  syslog: vcap.services.mysql.warden
  
  level: debug
network:
  pool_start_address: 10.254.0.0
  pool_size: 4096
user:
  pool_start_uid: 10000
  pool_size: 4096
