---

capacity: 40
plan: '200'
local_db: sqlite3:/var/vcap/store/postgresql_node.db

base_dir: /var/vcap/store/postgresql_data

mbus: nats://nats:z2b3ij3122@10.42.246.11:4222
index: 0
logging:
  level: debug
  file: /var/vcap/sys/log/postgresql_node/postgresql_node.log
  
  syslog: vcap.postgresql_node
  
pid: /var/vcap/sys/run/postgresql_node/postgresql_node.pid
node_id: postgresql_node_200_0
supported_versions: ['9.1']
default_version: '9.1'

max_db_size: 2560
max_long_query: 4
max_long_tx: 20
max_db_conns: 30
postgresql:

  '9.1':
   host: 127.0.0.1
   user: vcap
   pass: vcap
   port: 5433
   database: postgres
   dump_bin: /var/vcap/packages/postgresql91/bin/pg_dump
   restore_bin: /var/vcap/packages/postgresql91/bin/pg_restore



migration_nfs: /var/vcap/services_migration
z_interval: 30
max_nats_payload: 1048576
fqdn_hosts: false
op_time_limit: 6

max_disk: 128
use_warden: true
warden:
  service_log_dir: /var/vcap/sys/service-log/postgresql
  service_script_dir: /var/vcap/jobs/postgresql_node_ng/bin
  service_conf_dir: /var/vcap/jobs/postgresql_node_ng/config
  service_bin_dir:
  
    '9.1': /var/vcap/packages/postgresql91
  
  image_dir: /var/vcap/store/postgresql_image
  service_start_timeout: 3
  filesystem_quota: false

  port_range:
    first: 15000
    last: 25000

m_interval: 10

