---

service_name: postgresql
local_db: sqlite3:/var/vcap/store/postgresql_node.db
backup_base_dir: /var/vcap/services_backup
backup_cmd: /var/vcap/packages/postgresql/bin/pg_dump -Fc --port=:port --host=:host --username=:user --file=:full_path/:name.dump :name
node_id: postgresql_node_200_0
timeout: 600
postgresql:
  host: localhost
  port: 5432
  user: vcap
  pass: vcap
  database: postgres
logging:
  file: /var/vcap/sys/log/postgresql_node/postgresql_backup.log
  level: debug
  
  syslog: vcap.postgresql_backup
  
pid: /var/vcap/sys/run/postgresql_node/postgresql_backup.pid

use_warden: true

